import "../globals.css";
import { Inter } from "next/font/google";
import Navbar from "../../components/layout/navbar";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Next Enroll",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen flex flex-col antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}

